const posts = [{
        "name": 'Betty Adrian Condarco',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/1.jpg',
        "id": '1',
        "message": '',
        "slug": 'bac',
        "tag": 'member',
    },
    {
        "name": 'Ernesto Alejandro Alarcon Arias',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/2.jpg',
        "id": '2',
        "message": '',
        "slug": 'eaaa',
        "tag": 'member',
    },
    {
        "name": 'Sheila Bertha Aquino Aragon',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/3.jpg',
        "id": '3',
        "message": '',
        "slug": 'sbaa',
        "tag": 'member',
    },
    {
        "name": 'Henry Alvaro Aranibar Alanoca',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/4.jpg',
        "id": '4',
        "message": '',
        "slug": 'haaa',
        "tag": 'member',
    },
    {
        "name": 'Sergio Andres Argandoña Cartagena',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/5.jpg',
        "id": '5',
        "message": '',
        "slug": 'saac',
        "tag": 'member',
    },
    {
        "name": 'Sebastian Auza Derpic',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/6.jpg',
        "id": '6',
        "message": '',
        "slug": 'sad',
        "tag": 'member',
    },
    {
        "name": 'Franco Giovanni Ayala Guerra',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/7.jpg',
        "id": '7',
        "message": '',
        "slug": 'fgag',
        "tag": 'member',
    },
    {
        "name": 'Sergio Blanco Espinoza',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/80aniv.jpg',
        "id": '8',
        "message": '',
        "slug": 'sbe',
        "tag": 'member',
    },
    {
        "name": 'Jonathan Lucas Butron Carvajal',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/9.jpg',
        "id": '9',
        "message": '',
        "slug": 'jlbc',
        "tag": 'member',
    },
    {
        "name": 'Daniela Calzadilla Rocha',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/10.jpg',
        "id": '10',
        "message": '',
        "slug": 'dcr',
        "tag": 'member',
    },
    {
        "name": 'Roger Rodrigo Caro Coca',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/80aniv.jpg',
        "id": '11',
        "message": '',
        "slug": 'rrcc',
        "tag": 'member',
    },
    {
        "name": 'Juan Luis Cespedes Pariente',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/12.jpg',
        "id": '12',
        "message": '',
        "slug": 'jlcp',
        "tag": 'member',
    },
    {
        "name": 'Nidia Delgadillo Campos',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/13.jpg',
        "id": '13',
        "message": '',
        "slug": 'ndc',
        "tag": 'member',
    },
    {
        "name": 'Estefany Carolina Flores Brun',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/14.jpg',
        "id": '14',
        "message": '',
        "slug": 'ecfb',
        "tag": 'member',
    },
    {
        "name": 'Pablo Ramiro Flores Portal',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/15.jpg',
        "id": '15',
        "message": '',
        "slug": 'prfp',
        "tag": 'member',
    },
    {
        "name": 'Mariana Jeanine Gonzales Del Castillo',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/16.jpg',
        "id": '16',
        "message": '',
        "slug": 'mjgdc',
        "tag": 'member',
    },
    {
        "name": 'Daniel Gonzalez Pinto',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/80aniv.jpg',
        "id": '17',
        "message": '',
        "slug": 'dgp',
        "tag": 'member',
    },
    {
        "name": 'Joselyn Diana Guardia Vargas',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/18.jpg',
        "id": '18',
        "message": '',
        "slug": 'jdgv',
        "tag": 'member',
    },
    {
        "name": 'Raquel Gaby Herrera Patzi',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/80aniv.jpg',
        "id": '19',
        "message": '',
        "slug": 'rghp',
        "tag": 'member',
    },
    {
        "name": 'Percy Kevin Irahola Marca',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/20.jpg',
        "id": '20',
        "message": '',
        "slug": 'pkim',
        "tag": 'member',
    },
    {
        "name": 'Alejandra Fabiola Laguna Canchari',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/80aniv.jpg',
        "id": '21',
        "message": '',
        "slug": 'aflc',
        "tag": 'member',
    },
    {
        "name": 'Julio Eliot Lucana Ramos',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/22.jpg',
        "id": '22',
        "message": '',
        "slug": 'jelr',
        "tag": 'member',
    },
    {
        "name": 'Diego Mauricio Lucero Sandoval',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/23.jpg',
        "id": '23',
        "message": '',
        "slug": 'dmls',
        "tag": 'member',
    },
    {
        "name": 'Israel David Luna Pita',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/24.jpg',
        "id": '24',
        "message": '',
        "slug": 'idlp',
        "tag": 'member',
    },
    {
        "name": 'Diego Marcelo Maldonado Vasquez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/25.jpg',
        "id": '25',
        "message": '',
        "slug": 'dmmv',
        "tag": 'member',
    },
    {
        "name": 'Sergio Alejandro Mansilla Jimenez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/26.jpg',
        "id": '26',
        "message": '',
        "slug": 'samj',
        "tag": 'member',
    },
    {
        "name": 'Cecilia Gabriela Mogrobejo Rodriguez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/27.jpg',
        "id": '27',
        "message": '',
        "slug": 'cgmr',
        "tag": 'member',
    },
    {
        "name": 'Dayana Ilsen Molina Zalles',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/28.jpg',
        "id": '28',
        "message": '',
        "slug": 'dimz',
        "tag": 'member',
    },
    {
        "name": 'Lenny Montes Choque',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/29.jpg',
        "id": '29',
        "message": '',
        "slug": 'lmc',
        "tag": 'member',
    },
    {
        "name": 'Pamela Angela Monthiel Togo',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/30.jpg',
        "id": '30',
        "message": '',
        "slug": 'pamt',
        "tag": 'member',
    },
    {
        "name": 'Aleida Laura Olivera Bustillos',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/31.jpg',
        "id": '31',
        "message": '',
        "slug": 'alob',
        "tag": 'member',
    },
    {
        "name": 'Luis Marcelo Panozo Goitia',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/32.jpg',
        "id": '32',
        "message": '',
        "slug": 'lmpg',
        "tag": 'member',
    },
    {
        "name": 'Rodrigo Andres Paz Terrazas',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/33.jpg',
        "id": '33',
        "message": '',
        "slug": 'rapt',
        "tag": 'member',
    },
    {
        "name": 'Jhonny Edwin Quilo Vidaurre',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/34.jpg',
        "id": '34',
        "message": '',
        "slug": 'jeqv',
        "tag": 'member',
    },
    {
        "name": 'Dayana Quiroz Bardales',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/35.jpg',
        "id": '35',
        "message": '',
        "slug": 'dqb',
        "tag": 'member',
    },
    {
        "name": ' Daniela Belen Rios Veizan',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/36.jpg',
        "id": '36',
        "message": '',
        "slug": 'dbrv',
        "tag": 'member',
    },
    {
        "name": 'Alejandra Lenny Rivera Garces',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/37.jpg',
        "id": '37',
        "message": '',
        "slug": 'alrg',
        "tag": 'member',
    },
    {
        "name": 'Cristina Andrea Rivera Zelaya',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/38.jpg',
        "id": '38',
        "message": '',
        "slug": 'carz',
        "tag": 'member',
    },
    {
        "name": 'Diego Ramiro Rodriguez Armaza',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/39.jpg',
        "id": '39',
        "message": '',
        "slug": 'drra',
        "tag": 'member',
    },
    {
        "name": 'Alejandro Rojas Prado',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/40.jpg',
        "id": '40',
        "message": '',
        "slug": 'arp',
        "tag": 'member',
    },
    {
        "name": 'Brian Teran Sangueza',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/41.jpg',
        "id": '41',
        "message": '',
        "slug": 'btz',
        "tag": 'member',
    },
    {
        "name": 'Cesar Martin Torrico Miranda',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/42.jpg',
        "id": '42',
        "message": '',
        "slug": 'cmtm',
        "tag": 'member',
    },
    {
        "name": 'Romina Alejandra Varas Ulloa',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/43.jpg',
        "id": '43',
        "message": '',
        "slug": 'ravu',
        "tag": 'member',
    },
    {
        "name": 'Jhenny Janette Vargas Alanez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/44.jpg',
        "id": '44',
        "message": '',
        "slug": 'jjva',
        "tag": 'member',
    },
    {
        "name": 'Sergio Luis Vasquez Romero',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/45.jpg',
        "id": '45',
        "message": '',
        "slug": 'slvr',
        "tag": 'member',
    },
    {
        "name": 'Adrian Velasco Balderrama',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/46.jpg',
        "id": '46',
        "message": '',
        "slug": 'avb',
        "tag": 'member',
    },
    {
        "name": 'Valeria Alejandra Zuleta Cruz',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/47.jpg',
        "id": '47',
        "message": '',
        "slug": 'vazc',
        "tag": 'member',
    },
    {
        "name": 'Gonzalo Oscar Alfaro Fernandez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/48.jpg',
        "id": '48',
        "message": '',
        "slug": 'goaf',
        "tag": 'member',
    },
    {
        "name": 'Lorena Susy Illanes Sanjines',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/49.jpg',
        "id": '49',
        "message": '',
        "slug": 'lsis',
        "tag": 'guest',
    },
    {
        "name": 'Nancy Nina',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/50.jpg',
        "id": '50',
        "message": '',
        "slug": 'nn1',
        "tag": 'guest',
    },
    {
        "name": 'Amalia Teran Alfaro',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/51.jpg',
        "id": '51',
        "message": '',
        "slug": 'ata',
        "tag": 'guest',
    },
    {
        "name": 'Fabricio Bayá Hinojosa',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/52.jpg',
        "id": '52',
        "message": '',
        "slug": 'fbh',
        "tag": 'guest',
    },
    {
        "name": 'Mario Escalante Saravia',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/53.jpg',
        "id": '53',
        "message": '',
        "slug": 'mjes',
        "tag": 'guest',
    },
    {
        "name": 'Gabriel Garcia Alvarez',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/54.jpg',
        "id": '54',
        "message": '',
        "slug": 'gga',
        "tag": 'guest',
    },
    {
        "name": 'Cristopher Ayala Orgaz',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/55.jpg',
        "id": '55',
        "message": '',
        "slug": 'cao',
        "tag": 'guest',
    },
    {
        "name": 'Juan Bernardo Montoya',
        "image": 'https://aas-senior2010.s3.amazonaws.com/profiles/56.jpg',
        "id": '56',
        "message": '',
        "slug": 'jbm',
        "tag": 'guest',
    }
];

// posts.forEach(post => {
// post.html = post.html.replace(/^\t{3}/gm, '');
// });

export default posts;